name: Deploy PROD to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    if: |
      github.event_name == 'push' && 
      github.ref == 'refs/heads/main' &&
      github.event.repository.fork == false
      runs-on: [ self-hosted, Linux, X64 ]

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --pull -t bookstore-backend:prod .

      - name: Restart container
        run: |
          docker rm -f bookstore-prod || true
          docker run -d --name bookstore-prod \
            -p 8080:8080 \
            -e SPRING_PROFILES_ACTIVE=prod \
            -e DB_PASSWORD_PROD='${{ secrets.DB_PASSWORD_PROD }}' \
            -e APP_JWT_SECRET='${{ secrets.APP_JWT_SECRET }}' \
            -e CLOUDINARY_CLOUD_NAME='${{ secrets.CLOUDINARY_CLOUD_NAME }}' \
            -e CLOUDINARY_API_KEY='${{ secrets.CLOUDINARY_API_KEY }}' \
            -e CLOUDINARY_API_SECRET='${{ secrets.CLOUDINARY_API_SECRET }}' \
            -e MAIL_HOST='${{ secrets.MAIL_HOST }}' \
            -e MAIL_PORT='${{ secrets.MAIL_PORT }}' \
            -e MAIL_USERNAME='${{ secrets.MAIL_USERNAME }}' \
            -e MAIL_PASSWORD='${{ secrets.MAIL_PASSWORD }}' \
            -e MAIL_FROM='${{ secrets.MAIL_FROM }}' \
            -e MAIL_FROM_NAME='${{ secrets.MAIL_FROM_NAME }}' \
            --restart unless-stopped \
            bookstore-backend:prod

      - name: Show container status
        run: docker ps --filter "name=bookstore-prod"