name: Deploy PROD to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [ self-hosted ]

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t bookstore-backend:prod .

      - name: Restart container
        run: |
          docker rm -f bookstore-prod || true
          docker run -d --name bookstore-prod \
            -p 8080:8080 \
            -e SPRING_PROFILES_ACTIVE=prod \
            -e DB_PASSWORD_PROD='${{ secrets.DB_PASSWORD_PROD }}' \
            -e APP_JWT_SECRET='${{ secrets.APP_JWT_SECRET }}' \
            --restart unless-stopped \
            bookstore-backend:prod

      - name: Show container status
        run: docker ps --filter "name=bookstore-prod"

      - name: Send telegram message on success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ðŸš€ DEPLOY OK (main)
            Actor: ${{ github.actor }}
            Repo: ${{ github.repository }}
            Ref: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send telegram message on failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ðŸ’¥ DEPLOY FAIL (main)
            Actor: ${{ github.actor }}
            Repo: ${{ github.repository }}
            Ref: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
