name: Deploy PROD to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [ self-hosted ]  # hoặc [self-hosted, ec2] nếu runner bạn có label "ec2"

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t bookstore-backend:prod .

      - name: Restart container
        run: |
          docker rm -f bookstore-prod || true
          docker run -d --name bookstore-prod \
            -p 8080:8080 \
            -e SPRING_PROFILES_ACTIVE=prod \
            -e DB_PASSWORD_PROD='${{ secrets.DB_PASSWORD_PROD }}' \
            -e APP_JWT_SECRET='${{ secrets.APP_JWT_SECRET }}' \
            --restart unless-stopped \
            bookstore-backend:prod

      - name: Show container status
        run: docker ps --filter "name=bookstore-prod"
